-- Migration: Add telegram chat id to businesses and create telegram_links table

CREATE TABLE IF NOT EXISTS public.telegram_links (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    business_id uuid references public.businesses(id) on delete cascade not null,
    token text not null unique,
    used boolean default false not null,
    expires_at timestamp with time zone not null
);

ALTER TABLE public.businesses
ADD COLUMN IF NOT EXISTS telegram_chat_id text;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS telegram_chat_id text;

ALTER PUBLICATION supabase_realtime ADD TABLE public.telegram_links;
